import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './vitest.setup.ts',
    coverage: {
      provider: 'v8',
      include: [
        'src/components/Chats/ChatsSegment.tsx',
        'src/components/Chats/HiddenChats.tsx',
        'src/components/Chats/NewChats.tsx',
        'src/components/Chats/OngoingChats.tsx',
        'src/components/CommunityProfileModal.tsx',
        'src/components/CreateEventModal.tsx',
        'src/components/CreatePostModal.tsx',
        'src/components/EditHiddenContentModal.tsx',
        'src/components/EmailSettingsModal.tsx',
        'src/components/EventsCalendar.tsx',
        'src/components/OnboardingCardBio.tsx',
        'src/components/OnboardingCardCovid.tsx',
        'src/components/OnboardingCardDone.tsx',
        'src/components/OnboardingCardGenderIdentity.tsx',
        'src/components/OnboardingCardLetsTalkAbout.tsx',
        'src/components/OnboardingCardLivedExperiences.tsx',
        'src/components/OnboardingCardLocationCoords.tsx',
        'src/components/OnboardingCardLocationLabel.tsx',
        'src/components/OnboardingCardLookingFor.tsx',
        'src/components/OnboardingCardName.tsx',
        'src/components/OnboardingCardPictures.tsx',
        'src/components/OnboardingCardProfilePic.tsx',
        'src/components/OnboardingCardPronouns.tsx',
        'src/components/ProfileCard.tsx',
        'src/components/RefreshmentsFiltersModal.tsx',
        'src/components/RefreshmentsPosts/CommentItem.tsx',
        'src/components/RefreshmentsPosts/Comments.tsx',
        'src/components/RefreshmentsPosts/OpenedPost.tsx',
        'src/components/RefreshmentsPosts/RefreshmentsPost.tsx',
        'src/components/SelfProfileV2.tsx',
        'src/constants/onboarding.ts',
        'src/hooks/utilities.ts',
        'src/components/TextModal.tsx',
        'src/pages/Activity/index.tsx',
        'src/pages/AgeVerificationFlow.tsx',
        'src/pages/Chats.tsx',
        'src/pages/CommunityOnboarding.tsx',
        'src/pages/Likes.tsx',
        'src/pages/OnboardingV2.tsx',
        'src/pages/PersonalProfile.tsx',
        'src/pages/Picksv2.tsx',
        'src/pages/PostDetails.tsx',
        'src/pages/Refreshments.tsx',
        'src/pages/Settings.tsx',
        'src/pages/SubmittedPosts.tsx',
      ],
    },
  },
});
