// Effective React Query Keys
// https://tkdodo.eu/blog/effective-react-query-keys#use-query-key-factories
// https://tkdodo.eu/blog/leveraging-the-query-function-context#query-key-factories

export const userQueryKeys = {
    all: ['profiles'],
    mutuals: ['mutuals'],
    mutuals_no_dialog: ['mutuals-no-dialog'],
    mutuals_no_dialog_paginated: ['mutuals-no-dialog-paginated'],
    mutuals_no_dialog_paginated_v3: ['mutuals-no-dialog-paginated-v3'],
    searched: (searched_name: string) => ['mutuals', searched_name ],
    incoming: ['incoming'],
    incoming_paginated: ['incoming-paginated'],
    incoming_status: (userId?: string | number) => ['incoming-status', userId],
    outgoing: ['outgoing'],
    notifications: ['notifications'],
    current: ['current'],
    global_current: ['global-current'],
    settings_current: ['settings-current'],
    refreshments_current: ['refreshments-current'],
    community_profiles: () => ['community-profile'],
    community_profile: (userId?: number | 'current') => [...userQueryKeys.community_profiles(), userId ?? 'current'],
    community_blocked_search: (query: string) => [...userQueryKeys.community_profiles(), 'blocked-search', query],
    moderation: () => [...userQueryKeys.current, 'moderation'],
    streak: () => ['streak'],
    limits: () => ['limits'],
    picks_with_filters: ['picks_with_filters'],
    picks_and_profiles: ['picks-and-profiles'],
    details: () => [...userQueryKeys.all, 'detail'],
    detail: (id: number) => [...userQueryKeys.details(), id],
    push_notification_settings: (id: number) => ['current', 'push_notification_settings'],
    saved_locations: () => ['saved-locations'],
    multiple_accounts: () => ['multiple-accounts'],
    my_comments: ['my-comments'],
    // pagination: (page: number) => [...userQueryKeys.all, 'pagination', page],
    // infinite: () => [...userQueryKeys.all, 'infinite'],
  };
